from enum import Enum


class Registration(Enum):
    ID_SERVIDOR_PORTAL = 1
    NOME = 2
    CPF = 3
    MATRICULA = 4
    DESCRICAO_CARGO = 5
    CLASSE_CARGO = 6
    REFERENCIA_CARGO = 7
    PADRAO_CARGO = 8
    NIVEL_CARGO = 9
    SIGLA_FUNCAO = 10
    NIVEL_FUNCAO = 11
    FUNCAO = 12
    CODIGO_ATIVIDADE = 13
    ATIVIDADE = 14
    OPCAO_PARCIAL = 15
    COD_UORG_LOTACAO = 16
    UORG_LOTACAO = 17
    COD_ORG_LOTACAO = 18
    ORG_LOTACAO = 19
    COD_ORGSUP_LOTACAO = 20
    ORGSUP_LOTACAO = 21
    COD_UORG_EXERCICIO = 22
    UORG_EXERCICIO = 23
    COD_ORG_EXERCICIO = 24
    ORG_EXERCICIO = 25
    COD_ORGSUP_EXERCICIO = 26
    ORGSUP_EXERCICIO = 27
    TIPO_VINCULO = 28
    SITUACAO_VINCULO = 29
    DATA_INICIO_AFASTAMENTO = 30
    DATA_TERMINO_AFASTAMENTO = 31
    REGIME_JURIDICO = 32
    JORNADA_DE_TRABALHO = 33
    DATA_INGRESSO_CARGOFUNCAO = 34
    DATA_NOMEACAO_CARGOFUNCAO = 35
    DATA_INGRESSO_ORGAO = 36
    DOCUMENTO_INGRESSO_SERVICOPUBLICO = 37
    DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO = 38
    DIPLOMA_INGRESSO_CARGOFUNCAO = 39
    DIPLOMA_INGRESSO_ORGAO = 40
    DIPLOMA_INGRESSO_SERVICOPUBLICO = 41
    UF_EXERCICIO = 42
